import { Metadata } from 'next'
import { Locale } from '@/i18n'
import { locales } from '@/i18n'

const baseUrl = 'https://tradecomparator.com'

// Configuration SEO par langue avec les mots-clés ciblés
export const seoConfig: Record<Locale, {
  title: string
  description: string
  keywords: string[]
}> = {
  en: {
    title: 'Trade Comparator - Compare Best Trading Platforms UK',
    description: 'Compare the best trading platforms UK: FCA regulated brokers, forex, crypto exchanges, CFD trading, and spread betting. Find the perfect platform for your trading needs.',
    keywords: [
      'best trading platforms UK',
      'FCA regulated brokers',
      'UK forex broker comparison',
      'compare crypto exchanges UK',
      'best tax-free spread betting platforms',
      'CFD trading platforms UK',
      'trading platforms',
      'forex brokers',
      'crypto exchanges',
      'trading comparison',
      'regulated brokers',
      'spread betting',
      // Mots-clés supplémentaires
      'best forex broker UK',
      'trading platform reviews',
      'compare forex brokers',
      'best CFD broker UK',
      'forex broker with demo account',
      'low spread forex broker',
      'best leverage forex broker',
      'binary options brokers UK',
      'prop trading firms UK',
      'copy trading platform',
      'social trading platform',
      'forex broker minimum deposit',
      'best trading app UK',
      'MT4 brokers UK',
      'MT5 brokers UK',
      'ESMA regulated brokers',
      'trading platform comparison tool',
      'best trading platform for beginners',
      'best crypto trading platform UK',
      'crypto exchange reviews',
      'forex broker fees comparison',
      'trading signals provider',
      'trading education platform',
    ],
  },
  fr: {
    title: 'Trade Comparator - Comparateur de Plateformes de Trading',
    description: 'Comparez les meilleures plateformes de trading : Forex, Crypto, Prop Firms et Options Binaires. Brokers régulés AMF, signaux de trading gratuits. Données à jour, avis vérifiés.',
    keywords: [
      'meilleur broker forex',
      'comparateur de plateformes de trading',
      'broker régulé AMF',
      'meilleure plateforme crypto',
      'comparatif courtiers en ligne',
      'trading CFD France',
      'prop firm fiable',
      'signaux de trading gratuits',
      'apprendre le trading',
      'trading',
      'forex',
      'crypto',
      'comparaison plateformes',
      'brokers régulés',
      // Mots-clés supplémentaires
      'meilleur broker forex français',
      'courtier en ligne France',
      'broker avec compte démo',
      'meilleur spread forex',
      'broker forex pas cher',
      'trading automatisé',
      'copy trading France',
      'social trading',
      'options binaires France',
      'meilleure plateforme trading France',
      'avis broker forex',
      'test broker forex',
      'guide trading débutant',
      'formation trading',
      'meilleur exchange crypto France',
      'plateforme crypto régulée',
      'trading CFD',
      'broker MT4 France',
      'broker MT5 France',
      'leverage trading',
      'meilleur broker pour débutant',
      'broker forex sans commission',
      'comparateur brokers forex',
      'meilleure plateforme trading crypto',
      'signaux trading gratuits',
      'prop trading',
    ],
  },
  es: {
    title: 'Trade Comparator - Comparador de Plataformas de Trading',
    description: 'Compara las mejores plataformas de trading: Forex, Crypto, Brokers regulados CNMV. Encuentra el broker perfecto con cuenta demo y curso de trading online.',
    keywords: [
      'mejor broker de forex',
      'comparador de plataformas de trading',
      'brokers regulados CNMV',
      'mejor plataforma para trading de criptomonedas',
      'bróker con cuenta demo',
      'opciones binarias España',
      'curso de trading online',
      'trading',
      'forex',
      'crypto',
      'comparador brokers',
      'brokers regulados',
      // Mots-clés supplémentaires
      'mejor broker forex España',
      'bróker forex barato',
      'broker con mejor spread',
      'trading CFD España',
      'copy trading España',
      'social trading',
      'broker MT4 España',
      'broker MT5 España',
      'mejor plataforma trading',
      'bróker para principiantes',
      'mejor leverage forex',
      'broker forex sin comisiones',
      'exchange de criptomonedas España',
      'plataforma crypto regulada',
      'señales de trading',
      'prop trading España',
      'bróker con apalancamiento',
      'comparador de brókers',
      'mejor broker forex 2024',
      'test broker forex',
      'avisos broker',
      'guía trading principiantes',
      'mejor app trading',
      'trading automático',
      'bróker confiable',
    ],
  },
  de: {
    title: 'Trade Comparator - Trading Plattform Vergleich',
    description: 'Vergleichen Sie die besten Trading-Plattformen: BaFin regulierte Broker, Forex, Krypto. Finden Sie die perfekte Plattform mit Demokonto und Prop Trading Firmen.',
    keywords: [
      'bester forex broker',
      'trading plattform vergleich',
      'BaFin regulierte broker',
      'beste krypto handelsplattform',
      'CFD trading Deutschland',
      'demokonto trading',
      'prop trading firmen',
      'trading',
      'forex',
      'krypto',
      'broker vergleich',
      'regulierte broker',
      // Mots-clés supplémentaires
      'bester forex broker Deutschland',
      'forex broker mit demokonto',
      'bester spread forex',
      'günstiger forex broker',
      'CFD broker Deutschland',
      'copy trading Deutschland',
      'social trading',
      'trading automatisiert',
      'broker MT4 Deutschland',
      'broker MT5 Deutschland',
      'beste trading app',
      'forex broker ohne gebühren',
      'beste leverage forex',
      'krypto exchange Deutschland',
      'regulierte krypto börse',
      'trading signale',
      'prop firm Deutschland',
      'broker für anfänger',
      'trading plattform test',
      'broker bewertung',
      'trading lernen',
      'trading kurs',
      'binäre optionen Deutschland',
      'beste trading plattform',
      'forex broker vergleich',
    ],
  },
  it: {
    title: 'Trade Comparator - Confronto Piattaforme Trading',
    description: 'Confronta le migliori piattaforme di trading: Broker regolamentati CONSOB, Forex, Crypto. Trova la piattaforma perfetta per principianti con segnali di trading.',
    keywords: [
      'miglior broker forex',
      'confronto piattaforme trading',
      'broker regolamentati CONSOB',
      'miglior exchange crypto',
      'piattaforma CFD Italia',
      'trading per principianti',
      'segnali di trading',
      'trading',
      'forex',
      'crypto',
      'confronto broker',
      'broker regolamentati',
      // Mots-clés supplémentaires
      'miglior broker forex Italia',
      'broker forex con conto demo',
      'broker con spread basso',
      'broker forex economico',
      'trading CFD Italia',
      'copy trading Italia',
      'social trading',
      'broker MT4 Italia',
      'broker MT5 Italia',
      'miglior piattaforma trading',
      'broker per principianti',
      'miglior leverage forex',
      'broker senza commissioni',
      'exchange criptovalute Italia',
      'piattaforma crypto regolamentata',
      'segnali trading gratis',
      'prop trading Italia',
      'trading automatico',
      'broker affidabile',
      'confronto broker forex',
      'miglior broker forex 2024',
      'test broker forex',
      'recensioni broker',
      'guida trading principianti',
      'corso trading online',
      'miglior app trading',
    ],
  },
  pt: {
    title: 'Trade Comparator - Comparador de Corretoras',
    description: 'Compare as melhores corretoras: Forex, Crypto, Corretoras reguladas CMVM. Encontre a melhor plataforma para day trade e trading de criptomoedas.',
    keywords: [
      'melhor corretora forex Portugal',
      'comparador de corretoras',
      'corretoras reguladas CMVM',
      'melhor corretora de forex Brasil',
      'corretora de criptomoedas',
      'comparativo de corretoras',
      'melhor plataforma para day trade',
      'trading',
      'forex',
      'crypto',
      'corretoras',
      'brokers regulados',
      // Mots-clés supplémentaires
      'melhor corretora forex',
      'corretora com conta demo',
      'corretora com melhor spread',
      'corretora forex barata',
      'trading CFD',
      'copy trading',
      'social trading',
      'corretora MT4',
      'corretora MT5',
      'melhor plataforma trading',
      'corretora para iniciantes',
      'melhor leverage forex',
      'corretora sem comissões',
      'exchange criptomoedas',
      'plataforma crypto regulada',
      'sinais de trading',
      'prop trading',
      'trading automatizado',
      'corretora confiável',
      'comparativo corretoras forex',
      'melhor corretora forex 2024',
      'teste corretora',
      'avaliação corretora',
      'guia trading iniciantes',
      'curso trading online',
      'melhor app trading',
      'day trading plataforma',
      'opções binárias',
    ],
  },
  nl: {
    title: 'Trade Comparator - Trading Platform Vergelijken',
    description: 'Vergelijk de beste trading platforms: AFM gereguleerde brokers, Forex, Crypto. Vind het perfecte platform voor CFD trading met betrouwbare trading cursus.',
    keywords: [
      'beste forex broker',
      'trading platform vergelijken',
      'AFM gereguleerde brokers',
      'beste crypto exchange Nederland',
      'CFD trading',
      'betrouwbare trading cursus',
      'trading',
      'forex',
      'crypto',
      'broker vergelijking',
      'gereguleerde brokers',
      // Mots-clés supplémentaires
      'beste forex broker Nederland',
      'forex broker met demorekening',
      'beste spread forex',
      'goedkope forex broker',
      'CFD broker Nederland',
      'copy trading Nederland',
      'social trading',
      'geautomatiseerd trading',
      'broker MT4 Nederland',
      'broker MT5 Nederland',
      'beste trading app',
      'forex broker zonder kosten',
      'beste leverage forex',
      'crypto exchange vergelijken',
      'gereguleerde crypto beurs',
      'trading signalen',
      'prop trading Nederland',
      'broker voor beginners',
      'trading platform test',
      'broker beoordeling',
      'trading leren',
      'trading cursus online',
      'binaire opties Nederland',
      'beste trading platform',
      'forex broker vergelijken',
    ],
  },
  pl: {
    title: 'Trade Comparator - Porównywarka Platform Tradingowych',
    description: 'Porównaj najlepsze platformy tradingowe: Brokerzy regulowani KNF, Forex, Krypto. Znajdź idealną platformę dla początkujących do tradingu CFD w Polsce.',
    keywords: [
      'najlepszy broker forex',
      'porównywarka platform tradingowych',
      'brokerzy regulowani KNF',
      'najlepsza platforma kryptowalutowa',
      'trading CFD Polska',
      'platforma do tradingu dla początkujących',
      'trading',
      'forex',
      'krypto',
      'porównanie brokerów',
      'regulowani brokerzy',
      // Mots-clés supplémentaires
      'najlepszy broker forex Polska',
      'broker forex z kontem demo',
      'broker z najlepszym spreadem',
      'tani broker forex',
      'broker CFD Polska',
      'copy trading Polska',
      'social trading',
      'zautomatyzowany trading',
      'broker MT4 Polska',
      'broker MT5 Polska',
      'najlepsza aplikacja tradingowa',
      'broker forex bez prowizji',
      'najlepsza dźwignia forex',
      'giełda kryptowalut Polska',
      'regulowana giełda krypto',
      'sygnały tradingowe',
      'prop trading Polska',
      'broker dla początkujących',
      'test platformy tradingowej',
      'ocena brokera',
      'nauka tradingu',
      'kurs tradingu online',
      'opcje binarne Polska',
      'najlepsza platforma tradingowa',
      'porównanie brokerów forex',
      'najlepszy broker forex 2024',
    ],
  },
}

// Génère les métadonnées SEO pour une locale donnée
export function generateMetadata(locale: Locale): Metadata {
  const config = seoConfig[locale]
  
  return {
    title: config.title,
    description: config.description,
    keywords: config.keywords.join(', '),
    alternates: {
      canonical: `${baseUrl}/${locale}`,
      languages: generateHreflangLinks(locale),
    },
    openGraph: {
      title: config.title,
      description: config.description,
      url: `${baseUrl}/${locale}`,
      siteName: 'Trade Comparator',
      locale: localeToHreflang(locale),
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: config.title,
      description: config.description,
    },
    verification: {
      google: 'o96Blh7AgUihtyl2bEuKBF1EKadtl8NU1OAf7sTEz8Q',
    },
    other: {
      'google-adsense-account': 'ca-pub-5343389597650456',
    },
  }
}

// Génère les liens hreflang pour toutes les langues
export function generateHreflangLinks(currentLocale: Locale): Record<string, string> {
  const links: Record<string, string> = {}
  
  locales.forEach((locale) => {
    const hreflang = localeToHreflang(locale)
    links[hreflang] = `${baseUrl}/${locale}`
  })
  
  // Ajouter la version x-default pointant vers l'anglais (version par défaut)
  links['x-default'] = `${baseUrl}/en`
  
  return links
}

// Convertit une locale en code hreflang (ex: 'fr' -> 'fr', 'pt' pourrait être 'pt-PT' ou 'pt-BR')
function localeToHreflang(locale: Locale): string {
  // Pour le moment, on utilise les codes simples
  // Vous pourriez vouloir séparer pt-pt et pt-br plus tard
  return locale
}

